### ISSUE TITLE
ft_14/ edit controllers in service api to returns map interface(along with status) of a location

### ISSUE THREAD

**Issue by 8080co** [Alahkaih/Project_2_Team_3#87]

**Comment by 8080co** [comment]
**Main objective**: 2 controllers that when give a country or state, returns status and map interface
Currently we have 
- methods to retrieve status
- methods to retrieve map of state
- 
Steps:
- [ ] create method to retrieve map of country
- [ ] add country map retrieve method to existing controller(getCountryStatus)
- [ ] create new controller with state map retrieve method and status retrieve using rest template call to Status API

**Comment by HarrisonFok** [comment]
Some weren't possible. Refer to https://github.com/Alahkaih/Project_2_Team_3/pull/89
